
#define WRITE2PORTBIT(PORTNO,BITPOS,BITLEVEL)  (PORTNO == 0) ? (BITLEVEL ? (IOSET0 = 1<<BITPOS) : (IOCLR0 = 1<<BITPOS)) \
																														 : BITLEVEL ? ((IOSET1 = 1<<BITPOS) : (IOCLR1 = 1<<BITPOS))

#define SETBIT(WORD,BITPOS) 	WORD |= 1<<BITPOS

#define READWRITEBIT(DWORD,DBIT,SWORD,SBIT) \
        DWORD=((DWORD&~(1<<DBIT))|(((SWORD>>SBIT)&1)<<DBIT))

#define READBIT(WORD,BITPOS) ((WORD>>BITPOS)&1)

#define WRITEBIT(WORD,BITPOS,BITLEVEL) \
        WORD=((WORD&~(1<<BITPOS))|(BITLEVEL<<BITPOS))
				
#define WRITEBYTE(WORD,BITPOS,BITLEVEL) \
        (WORD = ((WORD & ~(0xFF << BITPOS)) | (BITLEVEL << BITPOS)))
				